### ISSUE TITLE
readme file is wrong (at least on Windows)

### ISSUE THREAD

**Issue by trickidicki** [potatolondon/djangae-scaffold#122]
The line:
`Run cd projectname && ./install_deps to install dependencies into a 'sitepackages' folder which is added to the path.`
is wrong, at least on Windows. Should be 
`cd projectname`
`python ../install_deps`

**Comment by adamalton** [comment]
The command in the REAME (`$ django-admin.py startproject...`) creates a folder called `projectname` (or whatever you set it to) and then inside that creates another folder called `projectname`.  So the instruction to then do `cd projectname && ./install_deps` is correct.

I think that the reason you need to do `python ../install_deps` (with the `../`) is because you've done `cd projectname` twice.
