### ISSUE TITLE
error python manage.py checksecure --settings=scaffold.settings_live

### ISSUE THREAD

**Issue by bituka** [potatolondon/djangae-scaffold#69]
This is very simple but a bit confusing for beginners like me. I think in the getting started steps, it should be 

python manage.py checksecure --settings=scaffold.settings_live

should be

python manage.py checksecure --settings=<my_new_app_name>.settings_live

**Comment by adamalton** [comment]
Really?  That doesn't seem right.  Have you moved the settings files out of the 'scaffold' folder?

**Comment by kkimball** [comment]
Took me a few minutes to figure this out as well. The issue is that people are instructed to `Run ./rename_scaffold_app my_new_app_name` before running `python manage.py checksecure --settings=scaffold.settings_live`.

The documentation should be updated to say run `python manage.py checksecure --settings=[my_new_app_name].settings_live` or change the order of the commands so that the rename script is after checksecure.

**Comment by spawnedc** [comment]
I just had the same issue. @kkimball's solution seems to be the best/easiest one.

**Comment by olasitarska** [comment]
This has been updated. Thanks for reporting everyone!
